// This file is generated by Slice Machine. Update with care!

import ImageSlider from './ImageSlider';
import TextBlock from './TextBlock';

export {
	ImageSlider,
	TextBlock,
};

export const components = {
	image_slider: ImageSlider,
	text_block: TextBlock,
};
