import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="Portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;800&display=swap"
          rel="stylesheet"
        />
        <link href="themes/prism-nord.css" rel="stylesheet" />
        {/* <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css"
        ></link> */}
      </Head>
      <body>
        <Main />
        <NextScript />
        <script src="prism.js"></script>
      </body>
    </Html>
  );
}
