import Head from "next/head";
// components
import About from "../pages/about";

export default function () {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <About />
      </section>
    </>
  );
}
