import { useState, useContext } from "react";
import Head from "next/head";
// components
import Header from "../components/header";
import Menu from "../components/menu";
import CustomCursor from "../components/feature/customCursor";
import About from "../pages/about";
// context
import { CursorContext } from "../context/cursor-context";

export default function () {
  const [toggleMenu, setToggleMenu] = useState(false);
  const { cursorType, cursorChangeHandler } = useContext(CursorContext);

  return (
    <>
      <Head>
        <title
          onMouseEnter={() => cursorChangeHandler("hovered")}
          onMouseLeave={() => cursorChangeHandler("")}
        >
          Portfolio
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomCursor cursorType={cursorType} />
      <nav>
        <Menu toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
        <Header setToggleMenu={setToggleMenu} />
      </nav>
      <section>
        <About />
      </section>
    </>
  );
}
