import { useState } from "react";
import Head from "next/head";
// components
import Header from "../components/header";
import CustomCursor from "../components/feature/customCursor";
// styles

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomCursor />
      <Header />
      <CustomCursor />
      <div>
        <h1>AESTHETICS</h1>
        <h2>H2</h2>
        <h3>Heading 3</h3>
        <h4>Heading 4</h4>
        <h5>Heading 5</h5>
        <h6>Heading 6</h6>
      </div>
      <p>
        Contrary to popular belief, Lorem Ipsum is not simply random text. It
        has roots in a piece of classical Latin literature from 45 BC, making it
        over 2000 years old. Richard McClintock, a Latin professor at
        Hampden-Sydney College in Virginia, looked up one of the more obscure
        Latin words, consectetur, from
      </p>
    </>
  );
}
